name: 'rem-ai'
services:

  ollama-gpu:
    container_name: ollama-gpu
    image: ollama/ollama:latest
    volumes:
      - "${OLLAMA_DATA_PATH:-./ai/data/ollama}:/root/.ollama"
    env_file: ./ai/.env
    ports:
      - 11434:11434
    runtime: nvidia
    environment:
      USER_GID: 1000
      USER_UID: 1000
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
    networks:
      rem-network:

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      USER_GID: 1000
      USER_UID: 1000
      MODEL_DOWNLOAD_DIR: /models
      OLLAMA_BASE_URL: http://ollama-gpu:11434
      LOG_LEVEL: info
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    env_file: ./ai/.env
    volumes:
      - "${OPENWEBUI_DATA_PATH:-./ai/data/openwebui/data}:/data"
      - "${OPENWEBUI_MODELS_PATH:-./ai/data/openwebui/models}:/models"
      - "${OPENWEBUI_APP_PATH:-./ai/data/openwebui/open-webui}:/app/backend/data"
    ports:
      - 8180:8080
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - ollama-gpu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      rem-network:
    restart: unless-stopped
    image: ghcr.io/ai-dock/stable-diffusion-webui:latest-cuda
    container_name: automatic1111
    ports:
      - "7860:7860"
      - "1111:1111"
    env_file: ./ai/.env
    volumes:
      - ${SD_MODELS_PATH:-./models/Stable-diffusion}:/workspace/stable-diffusion-webui/models/Stable-diffusion
      - ${SD_LORA_MODELS_PATH:-./models/Lora}:/workspace/stable-diffusion-webui/models/Lora
      - ${SD_VAE_MODELS_PATH:-./models/VAE}:/workspace/stable-diffusion-webui/models/VAE
      - ${SD_CONTROLNET_MODELS_PATH:-./models/ControlNet}:/workspace/stable-diffusion-webui/models/ControlNet
      - ${SD_OUTPUT_PATH:-./outputs}:/workspace/stable-diffusion-webui/outputs
      - ${SD_EXTENSIONS_PATH:-./extensions}:/workspace/stable-diffusion-webui/extensions
    environment:
      - CLI_ARGS=--xformers --api --listen
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=video,compute,utility
      - WEBUI_URL=${SD_URL:-http://localhost:1111}
    networks:
      rem-network:
    runtime: nvidia
    restart: unless-stopped

networks:
  rem-network:
    external: true
    name: rem-network
