name: rem-proxy
services:

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      TZ: "Etc/UTC"
    volumes:
      - "${NGINX_DATA_PATH:-./proxy/nginx/data}:/data"
      - "${NGINX_CERT_PATH:-./proxy/nginx/letsencrypt}:/letsencrypt"
    profiles:
      - nginx
    networks:
      rem-network:
  
  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    env_file: ./proxy/.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS}
      TOKEN: ${DUCKDNS_TOKEN}
    networks: 
      rem-network:

networks:
  rem-network:
    external: true
    name: rem-network