name: rem-auth
services:
  authelia:
    container_name: 'authelia'
    image: 'authelia/authelia'
    restart: 'unless-stopped'
    networks:
      rem-network:
    volumes:
      - './config/authelia:/config'
    environment:
      TZ: 'Etc/UTC'

networks:
  rem-network:
    external: true
    name: rem-network