name: rem-media
services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
    volumes:
      - "${JELLYFIN_CONFIG_PATH:-./data/jellyfin/config}:/config"
      - "${MEDIA_SERIES_PATH}:/data/series"
      - "${MEDIA_MOVIES_PATH}:/data/movies"
      - "${MEDIA_ANIME_PATH}:/data/anime"
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
    runtime: nvidia
    networks:
      rem-network:

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - "${SONARR_CONFIG_PATH:-./data/sonarr/config}:/config"
      - "${MEDIA_SERIES_PATH}:/series"
      - "${MEDIA_ANIME_PATH}:/anime"
      - "${MEDIA_DOWNLOADS_PATH}:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      rem-network:

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - "${RADARR_CONFIG_PATH:-./data/radarr/config}:/config"
      - "${MEDIA_MOVIES_PATH}:/movies"
      - "${MEDIA_DOWNLOADS_PATH}:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      rem-network:

  seerr:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    environment:
      LOG_LEVEL: info
      TZ: Etc/UTC
      PORT: 5055
    ports:
      - 5055:5055
    volumes:
      - "${SEERR_CONFIG_PATH:-./data/seerr/config}:/app/config"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      rem-network:

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - ${BAZARR_CONFIG_PATH:-./data/bazarr/config}:/config
      - ${MEDIA_MOVIES_PATH}:/movies 
      - ${MEDIA_SERIES_PATH}:/series
      - ${MEDIA_ANIME_PATH}:/anime
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      rem-network:
    
  configarr:
    image: ghcr.io/raydak-labs/configarr:latest
    container_name: configarr
    environment:
      USER_UID: 1000
      USER_GID: 1000
      TZ: Etc/UTC
    volumes:
      - "${CONFIGARR_CONFIG_PATH:-./data/configarr/config}:/app/config" # Contains the config.yml and secrets.yml
      - "${CONFIGARR_REPOS_PATH:-./data/configarr/dockerrepos}:/app/repos" # Cache repositories
      - "${CONFIGARR_CUSTOM_CFS_PATH:-./data/configarr/custom/cfs}:/app/cfs" # Optional if custom formats locally provided
      - "${CONFIGARR_CUSTOM_TEMPLATES:-./data/configarr/custom/templates}:/app/templates" # Optional if custom templates
    profiles:
      - config
    networks:
      rem-network:

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      WEBUI_PORT: 8080
      TORRENTING_PORT: 53565
    volumes:
      - "${TORRENT_CONFIG_PATH:-./data/qbittorrent/config}:/config"
      - "${MEDIA_DOWNLOADS_PATH}:/downloads"
    ports:
      - 8080:8080
      - 53565:53565
      - 53565:53565/udp
    restart: unless-stopped
    networks:
      rem-network:

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    volumes:
      - "${PROWLARR_CONFIG_PATH:-./data/prowlarr/config}:/config"
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      rem-network:

  jackett:
    image: lscr.io/linuxserver/jackett:0.24.1616
    container_name: jackett
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      AUTO_UPDATE: true
      RUN_OPTS: 
    volumes:
      - "${JACKETT_CONFIG_PATH:-./data/jackett/config}:/config"
      - "${MEDIA_DOWNLOADS_PATH}:/downloads"
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      rem-network:

  byparr:
    container_name: byparr
    image: ghcr.io/thephaseless/byparr:latest
    restart: unless-stopped
    init: true
    networks:
      rem-network:
    profiles:
      - bypass

  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest
    user: 1000:1000
    volumes:
      - "${MEDIA_ANIME_PATH}:/anime"
      - "${MEDIA_SERIES_PATH}:/series"
      - "${MEDIA_MOVIES_PATH}:/movies"
    environment:
      TZ: Etc/UTC
    ports:
      - 6246:6246
    restart: unless-stopped
    networks:
      rem-network:

  subgenai:
    image: 'mccloud/subgen:latest'
    container_name: subgenai
    volumes:
      - "${SUBGEN_MODEL_PATH:-./data/subgen/models}/models:/subgen/models"
      - "${SUBGEN_ENV_PATH:-./media/subgen.env}:/subgen/subgen.env:ro"
    environment:
      LOG_LEVEL: debug
      NAME_SERVERS: 9.9.9.9
      PROCADDEDMEDIA: true
      PROCMEDIAONPLAY: false
      JELLYFINTOKEN: ${SUBGEN_TOKEN:?Token is required}
      JELLYFINSERVER: 'http://jellyfin:8096'
      CONCURRENT_TRANSCRIPTIONS: 2
      USE_PATH_MAPPING: false
      MODEL_PATH: ./models
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
    runtime: nvidia
    networks:
      rem-network:

  lingarr:
    image: ghcr.io/lingarr-translate/lingarr:latest # or lingarr/lingarr:latest
    container_name: lingarr
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: http://+:9876
      DB_CONNECTION: mysql
      DB_HOST: lingarr-db
      DB_PORT: 3306
      DB_DATABASE: ${LINGARR_DATABASE:-lingarr}
      DB_USERNAME: ${LINGARR_DATABASE_USER:-lingarr}
      DB_PASSWORD: ${LINGARR_DATABASE_PASSWORD:-lingarr}
    ports:
      - "9876:9876"
    volumes:
      - "${MEDIA_ANIME_PATH}:/anime"
      - "${MEDIA_SERIES_PATH}:/series"
      - "${MEDIA_MOVIES_PATH}:/movies"
      - "${LINGARR_CONFIG_PATH:-./data/lingarr/config}:/app/config"
    networks:
      rem-network:
    depends_on:
      lingarr-db:
        condition: service_healthy

  lingarr-db:
    image: mariadb:latest
    container_name: lingarr-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${LINGARR_DATABASE:-lingarr}
      MYSQL_USER: ${LINGARR_DATABASE_USER:-lingarr}
      MYSQL_PASSWORD: ${LINGARR_DATABASE_PASSWORD:-lingarr}
      MYSQL_ROOT_PASSWORD: ${LINGARR_DATABASE_ROOT_PASSWORD:-lingarr} 
    volumes:
      - ${LINGARR_DATABASE_PATH:-./data/lingarr-database/data}:/var/lib/mysql
    networks:
      rem-network:
    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      interval: 10s
      timeout: 5s
      retries: 5

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    ports:
      - "11011:11011"
    volumes:
      - "${CLEANUPARR_CONFIG_PATH:-./data/cleanuparr/config}:/config"
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Etc/UTC
    networks:
      rem-network:

networks:
  rem-network:
    external: true
    name: rem-network