theme: 'auto'

jwt_secret: '{{ env "LLDAP_JWT_SECRET" }}'

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false

log:
  level: debug

totp:
  issuer: 'auth.{{ env "SESSION_DOMAIN" }}'
  period: 30
  skew: 1

identity_validation:
  reset_password:
    jwt_secret: '{{ env "RESET_PASSWORD_JWT_SECRET" }}'

authentication_backend:
  ldap:
    address: 'ldap://lldap:3890'
    implementation: 'custom'
    base_dn: '{{ env "LLDAP_BASE_DN" }}'
    additional_users_dn: 'ou=people'
    users_filter: '(&({username_attribute}={input})(objectClass=person))'
    username_attribute: 'uid'
    mail_attribute: 'mail'
    display_name_attribute: 'cn'
    additional_groups_dn: 'ou=groups'
    groups_filter: '(member={dn})'
    group_name_attribute: 'cn'
    user: '{{ env "LDAP_ADMIN_USER" }}'
    password: '{{ env "LDAP_ADMIN_PASSWORD" }}'

access_control:
  default_policy: 'one_factor'

session:
  name: 'authelia_session'
  cookies:
    - domain: '{{ env "SESSION_DOMAIN" }}'
      authelia_url: 'https://auth.{{ env "SESSION_DOMAIN" }}'
      default_redirection_url: 'https://{{ env "SESSION_DOMAIN" }}'
      expiration: '3M'
      inactivity: '1M'
      remember_me: '1y'

regulation:
  max_retries: 5
  find_time: '2 minutes'
  ban_time: '15 minutes'

storage:
  encryption_key: '{{ env "STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: '/config/db.sqlite3'

notifier:
  filesystem:
    filename: '/config/notification.txt'

identity_providers:
  oidc:
    hmac_secret: '{{ env "OIDC_HMAC_SECRET" }}'
    jwks:
      - key: |
          {{ secret "/config/secrets/oidc_private_key.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: 'portainer'
        client_name: 'Portainer'
        client_secret: '{{ env "PORTAINER_CLIENT_SECRET_HASH" }}'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://portainer.katarem.duckdns.org'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'
      - client_id: 'jellyfin'
        client_name: 'Jellyfin'
        client_secret: '{{ env "JELLYFIN_CLIENT_SECRET_HASH" }}'
        public: false
        authorization_policy: 'one_factor'
        redirect_uris:
          - 'https://media.katarem.duckdns.org'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        response_types:
          - 'code'
        grant_types:
          - 'authorization_code'
        access_token_signed_response_alg: 'none'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
