name: 'rem-rose'
services:
  flight-watcher:
    container_name: flight-watcher
    image: katarem/flight-watcher:1.0.0
    restart: until-restart
    environment:
      DB_ENGINE: postgres
      DB_HOST: fw-db
      DB_PORT: 10671
      DB_NAME: flight_watcher
      DB_USER: ${FLIGHT_WATCHER_DB_USER:-fw_user}
      DB_PASSWORD: ${FLIGHT_WATCHER_DB_PASSWORD:-password123}
    ports: 
      - 10670:8000
    networks:
      rem-network:
    
  flight-watcher-db:
    container_name: fw-db
    image: postgres:latest
    restart: until-restart
    environment:
      POSTGRES_PASSWORD: ${FLIGHT_WATCHER_DB_PASSWORD:-password123}
      POSTGRES_USER: ${FLIGHT_WATCHER_DB_USER:-fw_user}
      POSTGRES_DATABASE_NAME: flight_watcher
    ports:
      - 10671:5432
    networks:
      rem-network:

networks:
  rem-network:
      external: true