name: 'rem-rose'
services:
  flight-watcher:
    container_name: flight-watcher
    image: katarem/flight-watcher:1.0.0
    restart: unless-stopped
    environment:
      DB_ENGINE: postgres
      DB_HOST: fw-db
      DB_PORT: 5432
      DB_NAME: flight_watcher
      DB_USER: ${FLIGHT_WATCHER_DB_USER:-fw_user}
      DB_PASSWORD: ${FLIGHT_WATCHER_DB_PASSWORD:-password123}
    ports: 
      - 10670:8000
    networks:
      rem-network:
    
  flight-watcher-db:
    container_name: fw-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${FLIGHT_WATCHER_DB_PASSWORD:-password123}
      POSTGRES_USER: ${FLIGHT_WATCHER_DB_USER:-fw_user}
      POSTGRES_DB: flight_watcher
    networks:
      rem-network:

  bot-ddlg:
    container_name: bot-ddlg
    env_file:
      - .env
    image: katarem/bot-ddlg:1.0.0
    restart: unless-stopped

  happy-1-month:
    container_name: rosa_gift
    image: katarem/happy-1-month-rosa:1.0.0
    restart: unless-stopped
    ports:
      - 10672:80
    networks:
      rem-network:

networks:
  rem-network:
      external: true