name: 'rem-ai'
services:

  ollama-gpu:
    container_name: ollama-gpu
    image: ollama/ollama:latest
    volumes:
      - "${OLLAMA_DATA_PATH:-./data/ollama}:/root/.ollama"
    ports:
      - 11434:11434
    runtime: nvidia
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL:-http://loki:3100}/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    environment:
      USER_GID: 1000
      USER_UID: 1000
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: video,compute,utility
    networks:
      rem-network:

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    environment:
      USER_GID: 1000
      USER_UID: 1000
      MODEL_DOWNLOAD_DIR: /models
      OLLAMA_BASE_URL: http://ollama-gpu:11434
      LOG_LEVEL: info
      WEBUI_SECRET_KEY: ${WEBUI_SECRET_KEY}
    logging:
      driver: loki
      options:
        loki-url: "${LOKI_URL:-http://loki:3100}/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - "${OPENWEBUI_DATA_PATH:-./data/openwebui/data}:/data"
      - "${OPENWEBUI_MODELS_PATH:-./data/openwebui/models}:/models"
      - "${OPENWEBUI_APP_PATH:-./data/openwebui/open-webui}:/app/backend/data"
    ports:
      - 8180:8080
    depends_on:
      - ollama-gpu
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      rem-network:
    restart: unless-stopped

networks:
  rem-network:
    external: true
    name: rem-network
