name: rem-files
services:
  copyparty:
    container_name: copyparty
    image: copyparty/ac
    volumes:
      - "${COPYPARTY_SHARE_PATH:-./data/copyparty}:/w"
      - "./config/copyparty:/cfg"
networks:
  rem-network:
    external: true