name: rem-files
services:
  copyparty:
    container_name: copyparty
    image: copyparty/ac
    volumes:
      - "${COPYPARTY_SHARE_PATH:-./data/copyparty}:/w"
      - "./config/copyparty:/cfg"
    ports:
      - 3923:3923
    networks:
      rem-network:
networks:
  rem-network:
    external: true